name: mapbox_core
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
author: long1eu <home@long1.eu>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
