name: mapbox_geojson
description: GsoJson
version: 0.0.2
author: long1eu <lung.razvan@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  path: ^1.6.4

  mapbox_core:
    git:
      url: https://github.com/long1eu/mapbox_dart
      path: mapbox_core

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.6.9
