name: mapbox_geojson
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com
author: long1eu <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: ^1.4.1
  built_value: any
  built_collection: any

  mapbox_core:
    git:
      url: https://github.com/long1eu/mapbox_dart
      path: mapbox_core

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  built_value_generator: 6.3.1
